sudo: required
services: docker
language: bash
env:
    matrix:
        - DISTRO=debian   BRANCH=bullseye    ARCH=amd64
        - DISTRO=debian   BRANCH=bullseye    ARCH=armhf
        - DISTRO=debian   BRANCH=bullseye    ARCH=arm64

before_script:
    - sudo apt-get -y install qemu-user-static binutils
script:
    - sudo ./update.sh -d "$DISTRO" -b "$BRANCH" -a "$ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push sandwichimg/$DISTRO ; fi
