sudo: required
services: docker
language: bash
env:
    matrix:
        - DISTRO=alpine   BRANCH=v3.11    ARCH=x86
        - DISTRO=alpine   BRANCH=v3.11    ARCH=x86_64
        - DISTRO=alpine   BRANCH=v3.11    ARCH=armhf
        - DISTRO=alpine   BRANCH=v3.11    ARCH=aarch64

        - DISTRO=alpine   BRANCH=edge     ARCH=x86
        - DISTRO=alpine   BRANCH=edge     ARCH=x86_64
        - DISTRO=alpine   BRANCH=edge     ARCH=armhf
        - DISTRO=alpine   BRANCH=edge     ARCH=aarch64

        - DISTRO=debian   BRANCH=buster   ARCH=i386
        - DISTRO=debian   BRANCH=buster   ARCH=amd64
        - DISTRO=debian   BRANCH=buster   ARCH=armhf
        - DISTRO=debian   BRANCH=buster   ARCH=arm64

        - DISTRO=ubuntu   BRANCH=focal    ARCH=i386
        - DISTRO=ubuntu   BRANCH=focal    ARCH=amd64
        - DISTRO=ubuntu   BRANCH=focal    ARCH=armhf
        - DISTRO=ubuntu   BRANCH=focal    ARCH=arm64

before_script:
    - sudo apt-get -y install qemu-user-static binutils
script:
    - sudo ./update.sh -d "$DISTRO" -b "$BRANCH" -a "$ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push sandwichimg/$DISTRO ; fi
