sudo: required
services: docker
language: bash
env:
    matrix:
        - DISTRO=alpine   BRANCH=v3.12    ARCH=x86
        - DISTRO=alpine   BRANCH=v3.12    ARCH=x86_64
        - DISTRO=alpine   BRANCH=v3.12    ARCH=armhf
        - DISTRO=alpine   BRANCH=v3.12    ARCH=aarch64
        - DISTRO=alpine   BRANCH=v3.12    ARCH=mips64

before_script:
    - sudo apt-get -y install qemu-user-static binutils
script:
    - sudo ./update.sh -d "$DISTRO" -b "$BRANCH" -a "$ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push sandwichimg/$DISTRO ; fi
